In [1]:
import pandas as pd
import numpy as np

In [2]:
lookup= pd.read_csv("sa2_lookup.csv",dtype={'SA2_CODE_2021': str})
lookup

,SA2_CODE_2021,SA2_NAME_2021,SA3_NAME,GCC_NAME
0,401011001,Adelaide,Adelaide City,Greater Adelaide
1,401011002,North Adelaide,Adelaide City,Greater Adelaide
2,401021003,Adelaide Hills,Adelaide Hills,Greater Adelaide
3,401021004,Aldgate - Stirling,Adelaide Hills,Greater Adelaide
4,401021005,Hahndorf - Echunga,Adelaide Hills,Greater Adelaide
...,...,...,...,...
171,407031168,Renmark Surrounds,Murray and Mallee,Rest of SA
172,407031169,The Coorong,Murray and Mallee,Rest of SA
173,407031170,Waikerie,Murray and Mallee,Rest of SA
174,497979799,Migratory - Offshore - Shipping (SA),Migratory - Offshore - Shipping (SA),Migratory - Offshore - Shipping (SA)
175,499999499,No usual address (SA),No usual address (SA),No usual address (SA)

In [3]:
lookup.head(10)

  SA2_CODE_2021           SA2_NAME_2021        SA3_NAME          GCC_NAME
0     401011001                Adelaide   Adelaide City  Greater Adelaide
1     401011002          North Adelaide   Adelaide City  Greater Adelaide
2     401021003          Adelaide Hills  Adelaide Hills  Greater Adelaide
3     401021004      Aldgate - Stirling  Adelaide Hills  Greater Adelaide
4     401021005      Hahndorf - Echunga  Adelaide Hills  Greater Adelaide
5     401021006     Lobethal - Woodside  Adelaide Hills  Greater Adelaide
6     401021007            Mount Barker  Adelaide Hills  Greater Adelaide
7     401021008  Mount Barker Surrounds  Adelaide Hills  Greater Adelaide
8     401021009                  Nairne  Adelaide Hills  Greater Adelaide
9     401021010    Uraidla - Summertown  Adelaide Hills  Greater Adelaide

In [4]:
lookup['GCC_NAME'].value_counts()

GCC_NAME
Greater Adelaide                        112
Rest of SA                               62
Migratory - Offshore - Shipping (SA)      1
No usual address (SA)                     1
Name: count, dtype: int64

In [5]:
adelaide= lookup[lookup['GCC_NAME']=='Greater Adelaide'].copy()
adelaide

    SA2_CODE_2021       SA2_NAME_2021        SA3_NAME          GCC_NAME
0       401011001            Adelaide   Adelaide City  Greater Adelaide
1       401011002      North Adelaide   Adelaide City  Greater Adelaide
2       401021003      Adelaide Hills  Adelaide Hills  Greater Adelaide
3       401021004  Aldgate - Stirling  Adelaide Hills  Greater Adelaide
4       401021005  Hahndorf - Echunga  Adelaide Hills  Greater Adelaide
..            ...                 ...             ...               ...
107     404031105              Fulham    West Torrens  Greater Adelaide
108     404031106            Lockleys    West Torrens  Greater Adelaide
109     404031107            Plympton    West Torrens  Greater Adelaide
110     404031108       Richmond (SA)    West Torrens  Greater Adelaide
111     404031109          West Beach    West Torrens  Greater Adelaide

[112 rows x 4 columns]

In [6]:
# we need to add r before opening quote
g02=pd.read_csv(r"D:\adelaide-bunnings-expansion\bunnings data analyst\Data\2021Census_G02_SA_SA2.csv",
                dtype={'SA2_CODE_2021': str})
g02

,SA2_CODE_2021,Median_age_persons,Median_mortgage_repay_monthly,Median_tot_prsnl_inc_weekly,Median_rent_weekly,Median_tot_fam_inc_weekly,Average_num_psns_per_bedroom,Median_tot_hhd_inc_weekly,Average_household_size
0,401011001,31,1733,726,400,2056,1.0,1365,1.8
1,401011002,39,1914,964,390,2653,0.8,1867,1.9
2,401021003,47,1733,792,300,2163,0.8,1905,2.7
3,401021004,44,2000,993,410,2708,0.8,2297,2.7
4,401021005,48,1900,804,345,2333,0.8,1926,2.6
...,...,...,...,...,...,...,...,...,...
171,407031168,44,1178,749,200,1786,0.8,1459,2.5
172,407031169,48,879,604,190,1372,0.7,1085,2.2
173,407031170,50,953,593,200,1363,0.7,1027,2.2
174,497979799,48,0,1812,0,0,0.0,0,0.0
175,499999499,0,0,0,0,0,0.0,0,0.0

In [7]:
# rename ugly column names
g02 = g02.rename(columns={
    'SA2_CODE_2021': 'SA2_CODE_2021',           
    'Median_age_persons': 'median_age',
    'Median_mortgage_repay_monthly': 'median_mortgage',
    'Median_tot_prsnl_inc_weekly': 'weekly_personal_income',
    'Median_rent_weekly': 'weekly_rent',
    'Median_tot_fam_inc_weekly': 'weekly_family_income',
    'Median_tot_hhd_inc_weekly': 'weekly_household_income',
    'Average_num_psns_per_bedroom': 'avg_persons_per_bedroom',
    'Average_household_size': 'avg_household_size'
})
# Keep only columns we need (drop the rest)
cols_to_keep = ['SA2_CODE_2021', 'median_age', 'weekly_personal_income',
                'weekly_household_income', 'weekly_rent', 'avg_household_size']

g02 = g02[cols_to_keep]
g02

,SA2_CODE_2021,median_age,weekly_personal_income,weekly_household_income,weekly_rent,avg_household_size
0,401011001,31,726,1365,400,1.8
1,401011002,39,964,1867,390,1.9
2,401021003,47,792,1905,300,2.7
3,401021004,44,993,2297,410,2.7
4,401021005,48,804,1926,345,2.6
...,...,...,...,...,...,...
171,407031168,44,749,1459,200,2.5
172,407031169,48,604,1085,190,2.2
173,407031170,50,593,1027,200,2.2
174,497979799,48,1812,0,0,0.0
175,499999499,0,0,0,0,0.0

In [8]:
# load g01 data as it contains population data
g01=pd.read_csv(r"D:\adelaide-bunnings-expansion\bunnings data analyst\Data\2021Census_G01_SA_SA2.csv",
                dtype={'SA2_CODE_2021':str})
g01

,SA2_CODE_2021,Tot_P_M,Tot_P_F,Tot_P_P,Age_0_4_yr_M,Age_0_4_yr_F,Age_0_4_yr_P,Age_5_14_yr_M,Age_5_14_yr_F,Age_5_14_yr_P,...,High_yr_schl_comp_Yr_8_belw_P,High_yr_schl_comp_D_n_g_sch_M,High_yr_schl_comp_D_n_g_sch_F,High_yr_schl_comp_D_n_g_sch_P,Count_psns_occ_priv_dwgs_M,Count_psns_occ_priv_dwgs_F,Count_psns_occ_priv_dwgs_P,Count_Persons_other_dwgs_M,Count_Persons_other_dwgs_F,Count_Persons_other_dwgs_P
0,401011001,9561,8647,18202,170,152,318,326,300,625,...,187,63,47,103,7441,7135,14573,3930,3077,7001
1,401011002,3213,3615,6823,91,92,184,175,153,325,...,68,9,7,14,2627,2760,5389,806,1220,2019
2,401021003,3569,3483,7051,166,154,320,442,393,833,...,144,0,3,3,3294,3257,6551,157,161,319
3,401021004,8950,9256,18208,468,407,880,1257,1336,2592,...,197,13,4,13,8395,8820,17221,262,285,545
4,401021005,2301,2418,4726,127,114,243,270,245,510,...,114,0,4,5,2089,2182,4265,184,239,420
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
171,407031168,2721,2359,5080,143,127,270,307,287,593,...,254,22,20,42,2436,2178,4613,293,179,467
172,407031169,2866,2607,5473,124,118,243,353,289,642,...,329,6,7,17,2479,2328,4807,343,270,610
173,407031170,3531,3111,6646,160,136,297,357,351,711,...,371,14,8,20,2963,2803,5767,601,355,960
174,497979799,12,0,12,0,0,0,0,0,0,...,0,0,0,0,0,0,0,34,0,34
175,499999499,1873,1506,3377,77,56,140,128,139,262,...,95,10,6,21,0,0,0,0,0,0

In [9]:
# we have more columns but we need only total population columns
pop=g01[['SA2_CODE_2021', 'Tot_P_P']].copy()
pop=pop.rename(columns={'Tot_P_P' : 'population'})
pop

    SA2_CODE_2021  population
0       401011001       18202
1       401011002        6823
2       401021003        7051
3       401021004       18208
4       401021005        4726
..            ...         ...
171     407031168        5080
172     407031169        5473
173     407031170        6646
174     497979799          12
175     499999499        3377

[176 rows x 2 columns]

In [10]:
# now we need to load store data to know which suburbs does store already exists
stores=pd.read_csv("bunnings_sa_stores.csv")
stores = stores[stores['suburb'] != 'Gepps Cross']
stores

,store_name,suburb,address,postcode,is_adelaide_metro,lat,lng
0,Bunnings Adelaide Airport,Adelaide Airport,James Schofield Drive,5950,Yes,-34.9398,138.5430
1,Bunnings Edwardstown,Edwardstown,1028-1042 South Road,5039,Yes,-34.9972,138.5679
2,Bunnings Gawler,Gawler,Tiver Road Main North Road,5118,Yes,-34.5995,138.7421
4,Bunnings Kent Town,Kent Town,63-65 Rundle Street,5067,Yes,-34.9218,138.6161
5,Bunnings Marion,Oaklands Park,297 Diagonal Road,5046,Yes,-35.0037,138.5586
6,Bunnings Mile End,Mile End,108 Railway Terrace,5031,Yes,-34.9245,138.5700
7,Bunnings Modbury,Modbury,933-945 North East Road,5092,Yes,-34.8352,138.6848
8,Bunnings Mount Barker,Mount Barker,2 Dutton Road,5251,Yes,-35.0691,138.8607
9,Bunnings Munno Para West,Munno Para West,600 Curtis Road,5115,Yes,-34.6638,138.6735
10,Bunnings Noarlunga,Noarlunga Centre,Goldsmith Drive Jackson Place,5168,Yes,-35.1409,138.4974
11,Bunnings Parafield,Parafield,911 Main North Road,5107,Yes,-34.7940,138.6302
12,Bunnings Prospect,Prospect,258-282 Churchill Road,5082,Yes,-34.8857,138.5956
13,Bunnings Reynella,Reynella,184 Old South Road,5161,Yes,-35.0921,138.5309
14,Bunnings Seaford,Seaford Meadows,21 Seaford Road,5169,Yes,-35.1895,138.4828
15,Bunnings Windsor Gardens,Windsor Gardens,432 North East Road,5087,Yes,-34.8633,138.6449
16,Bunnings Woodville,Woodville,920 Port Road,5011,Yes,-34.8890,138.5397
17,Bunnings Berri,Berri,Old Sturt Highway,5343,No,-34.2866,140.6058
18,Bunnings Mt Gambier,Mount Gambier,18 Wireless Road West,5290,No,-37.8191,140.7591
19,Bunnings Murray Bridge,Murray Bridge,38-50 Adelaide Road,5253,No,-35.1232,139.2687
20,Bunnings Port Augusta,Port Augusta,Stirling Road,5700,No,-32.4896,137.7693
21,Bunnings Port Lincoln,Port Lincoln,12 London Street,5606,No,-34.7256,135.8650
22,Bunnings Victor Harbor,Victor Harbor,45 Adelaide Road,5211,No,-35.5446,138.6210

In [11]:
# now its time to merge all files into one master file
master = adelaide[['SA2_CODE_2021', 'SA2_NAME_2021', 'SA3_NAME']].copy()
# we merge g02 to get income
master = master.merge(g02, on='SA2_CODE_2021', how='left')
# merge pop to get population
master = master.merge(pop, on='SA2_CODE_2021', how='left')
master

,SA2_CODE_2021,SA2_NAME_2021,SA3_NAME,median_age,weekly_personal_income,weekly_household_income,weekly_rent,avg_household_size,population
0,401011001,Adelaide,Adelaide City,31,726,1365,400,1.8,18202
1,401011002,North Adelaide,Adelaide City,39,964,1867,390,1.9,6823
2,401021003,Adelaide Hills,Adelaide Hills,47,792,1905,300,2.7,7051
3,401021004,Aldgate - Stirling,Adelaide Hills,44,993,2297,410,2.7,18208
4,401021005,Hahndorf - Echunga,Adelaide Hills,48,804,1926,345,2.6,4726
...,...,...,...,...,...,...,...,...,...
107,404031105,Fulham,West Torrens,44,812,1753,315,2.5,2920
108,404031106,Lockleys,West Torrens,40,827,1635,300,2.4,13452
109,404031107,Plympton,West Torrens,36,794,1551,300,2.3,26480
110,404031108,Richmond (SA),West Torrens,37,774,1555,325,2.3,17022
111,404031109,West Beach,West Torrens,45,896,1746,320,2.4,5175

In [12]:
# now we need to merge bunnings count but we focusing adelaide metro stores
stores_adelaide = stores[stores['is_adelaide_metro'] == 'Yes'].copy()
#mapping store suburb names to ABS SA2 name
name_mapping = {
    'Adelaide Airport':  'Adelaide Airport',
    'Edwardstown':       'Edwardstown',
    'Gawler':            'Gawler - South',
    'Kent Town':         'Norwood (SA)',
    'Oaklands Park':     'Warradale',
    'Mile End':          'Richmond (SA)',
    'Modbury':           'Hope Valley - Modbury',
    'Mount Barker':      'Mount Barker',
    'Munno Para West':   'Munno Para West - Angle Vale',
    'Noarlunga Centre':  'Christies Beach',
    'Parafield':         'Parafield',
    'Prospect':          'Prospect',
    'Reynella':          'Reynella',
    'Seaford Meadows':   'Seaford - Seaford Meadows',
    'Windsor Gardens':   'Windsor Gardens',
    'Woodville':         'Woodville - Cheltenham',
}

stores_adelaide['sa2_matched'] = stores_adelaide['suburb'].map(name_mapping)
stores_adelaide

,store_name,suburb,address,postcode,is_adelaide_metro,lat,lng,sa2_matched
0,Bunnings Adelaide Airport,Adelaide Airport,James Schofield Drive,5950,Yes,-34.9398,138.5430,Adelaide Airport
1,Bunnings Edwardstown,Edwardstown,1028-1042 South Road,5039,Yes,-34.9972,138.5679,Edwardstown
2,Bunnings Gawler,Gawler,Tiver Road Main North Road,5118,Yes,-34.5995,138.7421,Gawler - South
4,Bunnings Kent Town,Kent Town,63-65 Rundle Street,5067,Yes,-34.9218,138.6161,Norwood (SA)
5,Bunnings Marion,Oaklands Park,297 Diagonal Road,5046,Yes,-35.0037,138.5586,Warradale
6,Bunnings Mile End,Mile End,108 Railway Terrace,5031,Yes,-34.9245,138.5700,Richmond (SA)
7,Bunnings Modbury,Modbury,933-945 North East Road,5092,Yes,-34.8352,138.6848,Hope Valley - Modbury
8,Bunnings Mount Barker,Mount Barker,2 Dutton Road,5251,Yes,-35.0691,138.8607,Mount Barker
9,Bunnings Munno Para West,Munno Para West,600 Curtis Road,5115,Yes,-34.6638,138.6735,Munno Para West - Angle Vale
10,Bunnings Noarlunga,Noarlunga Centre,Goldsmith Drive Jackson Place,5168,Yes,-35.1409,138.4974,Christies Beach
11,Bunnings Parafield,Parafield,911 Main North Road,5107,Yes,-34.7940,138.6302,Parafield
12,Bunnings Prospect,Prospect,258-282 Churchill Road,5082,Yes,-34.8857,138.5956,Prospect
13,Bunnings Reynella,Reynella,184 Old South Road,5161,Yes,-35.0921,138.5309,Reynella
14,Bunnings Seaford,Seaford Meadows,21 Seaford Road,5169,Yes,-35.1895,138.4828,Seaford - Seaford Meadows
15,Bunnings Windsor Gardens,Windsor Gardens,432 North East Road,5087,Yes,-34.8633,138.6449,Windsor Gardens
16,Bunnings Woodville,Woodville,920 Port Road,5011,Yes,-34.8890,138.5397,Woodville - Cheltenham

In [13]:
# Count per SA2
store_counts = (
    stores_adelaide
    .groupby('sa2_matched') # put stores into buckets- one bucket for one suburb
    .size()                  # cpunt how many stores in each bucket
    .reset_index              # turn result into proper table(not a series)
    (name='bunnings_count') # name coulumn ' bunnings_count'
    .rename(columns={'sa2_matched': 'SA2_NAME_2021'})) 

# Merge into master
master = master.merge(store_counts, on='SA2_NAME_2021', how='left')
master['bunnings_count'] = master['bunnings_count'].fillna(0).astype(int)
master

,SA2_CODE_2021,SA2_NAME_2021,SA3_NAME,median_age,weekly_personal_income,weekly_household_income,weekly_rent,avg_household_size,population,bunnings_count
0,401011001,Adelaide,Adelaide City,31,726,1365,400,1.8,18202,0
1,401011002,North Adelaide,Adelaide City,39,964,1867,390,1.9,6823,0
2,401021003,Adelaide Hills,Adelaide Hills,47,792,1905,300,2.7,7051,0
3,401021004,Aldgate - Stirling,Adelaide Hills,44,993,2297,410,2.7,18208,0
4,401021005,Hahndorf - Echunga,Adelaide Hills,48,804,1926,345,2.6,4726,0
...,...,...,...,...,...,...,...,...,...,...
107,404031105,Fulham,West Torrens,44,812,1753,315,2.5,2920,0
108,404031106,Lockleys,West Torrens,40,827,1635,300,2.4,13452,0
109,404031107,Plympton,West Torrens,36,794,1551,300,2.3,26480,0
110,404031108,Richmond (SA),West Torrens,37,774,1555,325,2.3,17022,1
111,404031109,West Beach,West Torrens,45,896,1746,320,2.4,5175,0

In [14]:
print(f"Suburbs WITH Bunnings: {(master['bunnings_count'] > 0).sum()}")
print(f"Suburbs WITHOUT Bunnings: {(master['bunnings_count'] == 0).sum()}")

Suburbs WITH Bunnings: 16
Suburbs WITHOUT Bunnings: 96

In [15]:
!pip install pyodbc sqlalchemy

Requirement already satisfied: pyodbc in c:\users\kiran\appdata\local\programs\python\python313\lib\site-packages (5.3.0)
Requirement already satisfied: sqlalchemy in c:\users\kiran\appdata\local\programs\python\python313\lib\site-packages (2.0.50)
Requirement already satisfied: greenlet>=1 in c:\users\kiran\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (3.5.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\kiran\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (4.12.2)

[notice] A new release of pip is available: 24.3.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [16]:
import pandas as pd
import pyodbc
from sqlalchemy import create_engine
from urllib.parse import quote_plus

server = "LAPTOP-QJVGB01O\SQLEXPRESS"
database= "adelaide_retail"

# Build the connection string for Windows Authentication
conn_str = (
    f"DRIVER={{ODBC Driver 17 for SQL Server}};"
    f"SERVER={server};"
    f"DATABASE={database};"
    f"Trusted_Connection=yes;"
)

# Wrap it so SQLAlchemy + pandas can use it
engine = create_engine(f"mssql+pyodbc:///?odbc_connect={quote_plus(conn_str)}")

<>:6: SyntaxWarning: invalid escape sequence '\S'
<>:6: SyntaxWarning: invalid escape sequence '\S'
C:\Users\kiran\AppData\Local\Temp\ipykernel_23364\3513890590.py:6: SyntaxWarning: invalid escape sequence '\S'
  server = "LAPTOP-QJVGB01O\SQLEXPRESS"

In [17]:
# Test it!
test = pd.read_sql("SELECT @@VERSION AS sql_server_version", engine)
print(" Connected to SQL Server!")
print(test.iloc[0, 0])

 Connected to SQL Server!
Microsoft SQL Server 2022 (RTM) - 16.0.1000.6 (X64)
	Oct  8 2022 05:58:25
	Copyright (C) 2022 Microsoft Corporation
	Express Edition (64-bit) on Windows 10 Home Single Language 10.0 <X64> (Build 26200: ) (Hypervisor)

In [18]:
#pushing master dataframe into ssms
master.to_sql('suburbs', engine, if_exists='replace', index=False)
check = pd.read_sql("SELECT COUNT(*) AS row_count FROM suburbs", engine)
print(f"Rows now in SQL Server: {check['row_count'][0]}")

Rows now in SQL Server: 112